#! /bin/bash

set -e

function _error() {
    echo "ERROR: $1" >&2
    exit 1
}

which python3 > /dev/null 2>&1 || _error "Python 3 not installed."

python3 -m venv .env

. start-env
pip install wheel
pip install -r requirements.txt
deactivate
